### ISSUE TITLE
[Sherry & Amy] 课程支持右滑取消和删除

### ISSUE THREAD

**Issue by t20731** [t20731/SFMoocWechatClient#27]
有人注册的课 支持取消 使用微信通知发送给所有人
取消注册的课程 status 为-1 不能在explore里面搜索到 进入课程详情时不能register 也不能start

没人注册的课程 支持删除

**Comment by lentty** [comment]
取消注册的课程 status 为-1 不能在explore里面搜索到  进入课程详情时不能register 也不能start
