### ISSUE TITLE
New Feature: 支持不同type的课程

### ISSUE THREAD

**Issue by t20731** [t20731/SFMoocWechatClient#28]
目前支持两种type: public 和  T2 ， UI 在创建和编辑的时候加一行Group的选择, 当前用户属于那些group才能拿到相应的group list. 所有人都属于public。
新建一张表group 里面有id, name  id 是session 中的type id中的外键
新建一张表user_group_map表 里面有 user_id group_id (外键)多对多关系用来track 一个group有哪些人(为了分清排行和权限控制) （都暂时写假数据）

To do list:
- 排行按不同的group来排行， 同一个group里面分积分排行和课程like排行
- 课程详情里面除了T2 其他都只支持checkin和like
- 只有T2的人才能看到公告和分享顺序

**Comment by wyjsally** [comment]
@lentty 现在create new session 的时候  init需要传进去userid去判断group。我需要把/session/init改成post不？还是有其他好方法？

**Comment by wyjsally** [comment]
我用了/init/{id}哦~

**Comment by wyjsally** [comment]
本周完成：
DB: 
group 和 user_group_map 表已创建。session表中type_id 的外键没创建成功。

后台：
1. /session/init/{userId} 获取包含user  group的信息
2. SessionDAOImpl  存储session的typeId信息
3.  /session/detail 把session的typeId传给前台。

前台：
1. /session/detail 当typeId = 1 (T2), showLottery:true,   showQuiz:true
2.  修改了init，将userId传给后台  /session/init/{userId}

**Comment by lentty** [comment]
排行UI  积分排行后台 @VickyJi0992 
课程Like排行 @wyjsally  点击课程到课程详情页面
